author: 'The Artifex (4r7if3x)'

name: 'Packster: JavaScript Action Runner'
description: 'Runs a custom JavaScript action'
branding:
  icon: play
  color: gray-dark

inputs:
  action:
    description: 'Action path'
    required: true

outputs:
  result:
    description: 'Action result'
    value: |-
      ${{
        runner.os == 'Windows' && steps.win.outputs.result || (
          runner.os == 'macOS' && steps.mac.outputs.result || steps.nix.outputs.result
        )
      }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        check-latest: true

    - name: Run Action
      if: ${{ runner.os == 'Linux' }}
      id: nix
      shell: bash
      env:
        INPUT_ACTION: ${{ inputs.action }}
      run: |
        bash "${GITHUB_ACTION_PATH}/scripts/run.sh"

    - name: Run Action
      if: ${{ runner.os == 'macOS' }}
      id: mac
      shell: zsh {0}
      env:
        INPUT_ACTION: ${{ inputs.action }}
      run: |
        zsh "${GITHUB_ACTION_PATH}/scripts/run.zsh"

    - name: Run Action
      if: ${{ runner.os == 'Windows' }}
      id: win
      shell: powershell
      env:
        INPUT_ACTION: ${{ inputs.action }}
      run: |
        powershell -File "${env:GITHUB_ACTION_PATH}\scripts\run.ps1
